# Generated by Django 3.1.2 on 2020-11-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='link',
            field=models.CharField(default=False, max_length=1000),
        ),
    ]
