# Generated by Django 3.1.2 on 2020-11-17 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_list_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='complete',
        ),
    ]
